gpu: 2
epochs: 200
lr: 0.0001
batch_size: 16
num_workers: 4
train_ratio: 0.8
val_ratio: 0.1
test_ratio: 0.1
patch_size: [32, 32]
window_size: 8
save_path: checkpoints/sample/FS
display_iter: 1
snapshot_iter: 50
patience: 100
dataset: FS

model:
  num_features: 128
  num_classes: 2
  back_method: resnet50
  hidden_dim: 256
  num_frame_layers: 3
  num_diff_layers: 1
  num_frames: 8
  num_patches: 49
  similarity_threshold: 0.8
  dropout_rate: 0.1
  multi_head: 8
  temporal_window: 2
